@Library('Jenkins-shared-library') _

def configMap = [
    PROJECT  : "expense",
    COMPONENT: "backend",
    GITREPO  : "https://github.com/Vamsi987dev/Expense-Backend.git",
    BRANCH   : "${env.BRANCH_NAME}",
    AWS_REGION: "us-east-1",
    ACCOUNT_ID: "222634367824"
]

nodejsCI(configMap)

